In [3]:
import importlib

import ibis
import polars as pl
from ibis import deferred as _
from polars.testing import assert_frame_equal

import datasets
import datasets.fake
import pvm
import pvm.fields
import pvm.formulas
import pvm.pvm
from pvm.fields import Field, QuantityField, RateField
from pvm.pvm import PVM

importlib.reload(pvm.formulas)
importlib.reload(pvm.pvm)
importlib.reload(datasets)
importlib.reload(pvm)
importlib.reload(datasets.fake)
pass
pvm.__version__

'0.0.3'

In [4]:
datasets.sales.cost_effects_by_country_sku

shape: (20, 21)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ country    ┆ sku  ┆ unit_cost_ ┆ cost_volum ┆ … ┆ unit_cost_ ┆ cost_volu ┆ yield_rat ┆ raw_mater │
│ ---        ┆ ---  ┆ 2020       ┆ e_2020     ┆   ┆ _effect__2 ┆ me__effec ┆ e__effect ┆ ial__effe │
│ str        ┆ str  ┆ ---        ┆ ---        ┆   ┆ 020        ┆ t__2020   ┆ __2020    ┆ ct__2020  │
│            ┆      ┆ f64        ┆ f64        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│            ┆      ┆            ┆            ┆   ┆ f64        ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Bouvet     ┆ SKU0 ┆ -13.451531 ┆ 230.105074 ┆ … ┆ 2469.36463 ┆ -2171.361 ┆ -57.70573 ┆ -2113.655 │
│ Island (Bo ┆      ┆            ┆            ┆   ┆ 8          ┆ 585       ┆ 3         ┆ 852       │
│ uvetoya)   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Bouvet     ┆ SKU1 ┆ -64.884743 ┆ 360.696298 ┆ … ┆ 611.895591 ┆ 5994.3617 ┆ 617.18637 ┆ 5377.1754 │
│ Island (Bo ┆      ┆            ┆            ┆   ┆            ┆ 88        ┆ 9         ┆ 1         │
│ uvetoya)   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Bouvet     ┆ SKU2 ┆ -64.251742 ┆ 493.595726 ┆ … ┆ 1205.62466 ┆ 7820.7893 ┆ 802.3811  ┆ 7018.4082 │
│ Island (Bo ┆      ┆            ┆            ┆   ┆ 4          ┆ 49        ┆           ┆ 49        │
│ uvetoya)   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Bouvet     ┆ SKU3 ┆ -56.269671 ┆ 387.563455 ┆ … ┆ 1014.35307 ┆ 8206.8502 ┆ -302.3244 ┆ 8509.1747 │
│ Island (Bo ┆      ┆            ┆            ┆   ┆ 5          ┆ 99        ┆ 65        ┆ 64        │
│ uvetoya)   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Bouvet     ┆ SKU4 ┆ -12.905885 ┆ 277.72621  ┆ … ┆ 562.816388 ┆ -3927.731 ┆ 135.24666 ┆ -4062.978 │
│ Island (Bo ┆      ┆            ┆            ┆   ┆            ┆ 414       ┆           ┆ 074       │
│ uvetoya)   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ Saint      ┆ SKU0 ┆ -9.663474  ┆ 420.360844 ┆ … ┆ -393.44991 ┆ -64.78492 ┆ -59.86445 ┆ -4.920468 │
│ Vincent    ┆      ┆            ┆            ┆   ┆ 5          ┆ 6         ┆ 8         ┆           │
│ and the    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Grenadin…  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Saint      ┆ SKU1 ┆ -64.987667 ┆ 650.982093 ┆ … ┆ -367.05552 ┆ 20368.084 ┆ 538.35489 ┆ 19829.729 │
│ Vincent    ┆      ┆            ┆            ┆   ┆ 3          ┆ 839       ┆ 3         ┆ 945       │
│ and the    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Grenadin…  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Saint      ┆ SKU2 ┆ -60.930184 ┆ 475.51546  ┆ … ┆ -586.97613 ┆ 3435.0447 ┆ -2.673328 ┆ 3437.7181 │
│ Vincent    ┆      ┆            ┆            ┆   ┆ 2          ┆ 75        ┆           ┆ 02        │
│ and the    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Grenadin…  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Saint      ┆ SKU3 ┆ -58.876735 ┆ 316.351098 ┆ … ┆ 203.78936  ┆ -13202.99 ┆ -294.6426 ┆ -12908.35 │
│ Vincent    ┆      ┆            ┆            ┆   ┆            ┆ 843       ┆ 98        ┆ 5732      │
│ and the    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Grenadin…  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Saint      ┆ SKU4 ┆ -15.354866 ┆ 196.530092 ┆ … ┆ 3196.72655 ┆ -5060.361 ┆ 5.727241  ┆ -5066.088 │
│ Vincent    ┆      ┆            ┆            ┆   ┆ 4          ┆ 18        ┆           ┆ 421       │
│ and the    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Grenadin…  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [43]:
price = RateField(
    "unit_price",
    definition=(_.volume * _.unit_price).sum() / _.volume.sum(),
    components=[
        QuantityField(
            "price_in_lc",
            definition=(_.volume * _.price_in_lc).sum() / _.volume.sum(),
        ),
        RateField(
            "fx_rate",
            definition=(_.volume * _.fx_rate * _.price_in_lc).sum() / (_.price_in_lc * _.volume).sum(),
        ),
    ],
)

revenue = Field(
    "revenue",
    definition=_.revenue.sum(),
    reconcile=False,
    components=[
        price,
        QuantityField(
            "volume",
            definition=_.volume.sum(),
        ),
        Field("flat_fee", definition=_.flat_fee.sum()),
    ],
)

In [44]:
con = ibis.polars.connect({"sales": datasets.sales.raw})
sales = con.table("sales")

obj = PVM().set_data(sales).set_periods(_.year, ["2020", "2021"]).set_hierarchy([_.customer, _.sku])

obj.set_graph(revenue)

In [ ]:
assert_frame_equal(
    obj.calculate_effects().to_polars().sort("customer", "sku"),
    datasets.sales.effects_by_customer_sku.sort("customer", "sku"),
    check_column_order=False,
    check_row_order=True,
    check_dtypes=False,
    atol=1e-2,
)

In [ ]:
unbound_table = ibis.table(sales.schema())
ibis.to_sql(obj.set_data(unbound_table).calculate_effects())

In [ ]:
obj.calculate_effects().to_polars().select(
    "sku",
    "country",
    "unit_price__effect__2020",
    "price_in_lc__effect__2020",
    "fx_rate__effect__2020",
).with_columns(
    (pl.col("unit_price__effect__2020") - pl.col("price_in_lc__effect__2020") - pl.col("fx_rate__effect__2020")).alias(
        "diff",
    ),
).sort(["country", "sku"])

shape: (20, 6)
┌──────┬───────────────────┬───────────────────┬───────────────────┬───────────────────┬───────────┐
│ sku  ┆ country           ┆ unit_price__effec ┆ price_in_lc__effe ┆ fx_rate__effect__ ┆ diff      │
│ ---  ┆ ---               ┆ t__2020           ┆ ct__2020          ┆ 2020              ┆ ---       │
│ str  ┆ str               ┆ ---               ┆ ---               ┆ ---               ┆ f64       │
│      ┆                   ┆ f64               ┆ f64               ┆ f64               ┆           │
╞══════╪═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪═══════════╡
│ SKU0 ┆ Bouvet Island     ┆ -245.058235       ┆ 221.171414        ┆ -465.975594       ┆ -0.254054 │
│      ┆ (Bouvetoya)       ┆                   ┆                   ┆                   ┆           │
│ SKU1 ┆ Bouvet Island     ┆ 775.666603        ┆ 3633.445595       ┆ -2856.300861      ┆ -1.478131 │
│      ┆ (Bouvetoya)       ┆                   ┆                   ┆                   ┆           │
│ SKU2 ┆ Bouvet Island     ┆ 1488.422966       ┆ 4013.257933       ┆ -2523.560357      ┆ -1.27461  │
│      ┆ (Bouvetoya)       ┆                   ┆                   ┆                   ┆           │
│ SKU3 ┆ Bouvet Island     ┆ -1632.4751        ┆ 2424.875364       ┆ -4055.173563      ┆ -2.176901 │
│      ┆ (Bouvetoya)       ┆                   ┆                   ┆                   ┆           │
│ SKU4 ┆ Bouvet Island     ┆ -1822.414223      ┆ -1480.970039      ┆ -341.218744       ┆ -0.225439 │
│      ┆ (Bouvetoya)       ┆                   ┆                   ┆                   ┆           │
│ …    ┆ …                 ┆ …                 ┆ …                 ┆ …                 ┆ …         │
│ SKU0 ┆ Saint Vincent and ┆ -1.24942          ┆ 509.947018        ┆ -511.49295        ┆ 0.296511  │
│      ┆ the Grenadin…     ┆                   ┆                   ┆                   ┆           │
│ SKU1 ┆ Saint Vincent and ┆ -1233.187334      ┆ 2225.256196       ┆ -3460.371041      ┆ 1.927511  │
│      ┆ the Grenadin…     ┆                   ┆                   ┆                   ┆           │
│ SKU2 ┆ Saint Vincent and ┆ -244.626223       ┆ 1678.173782       ┆ -1923.883343      ┆ 1.083338  │
│      ┆ the Grenadin…     ┆                   ┆                   ┆                   ┆           │
│ SKU3 ┆ Saint Vincent and ┆ -664.920275       ┆ 1124.224275       ┆ -1790.126767      ┆ 0.982217  │
│      ┆ the Grenadin…     ┆                   ┆                   ┆                   ┆           │
│ SKU4 ┆ Saint Vincent and ┆ -102.270096       ┆ -5.874197         ┆ -96.449269        ┆ 0.053371  │
│      ┆ the Grenadin…     ┆                   ┆                   ┆                   ┆           │
└──────┴───────────────────┴───────────────────┴───────────────────┴───────────────────┴───────────┘